import type { Metadata } from "next";
import { Playfair, lato } from "@/app/ui/fonts";
import "@/app/ui/global.css";
import { Providers } from './providers';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${Playfair.variable} ${lato.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
