import {Product} from "@/app/lib/definitions";

export const products: Product[] = [
    {
        id: "1",
        name: "Handwoven Basket",
        imageUrl: "/images/products/prod1.jpeg",
        description: "A beautifully handwoven basket made from natural materials.",
        price: 25.99,
        artist: "Maria Lopez",
        category: "Home Decor",
    },
    {
        id: "2",
        name: "Ceramic Mug",
        imageUrl: "/images/products/prod2.jpeg",
        description: "A handmade ceramic mug, perfect for your morning coffee.",
        price: 14.99,
        artist: "Jorge Ramirez",
        category: "Kitchenware",
    },
    {
        id: "3",
        name: "Wooden Sculpture",
        imageUrl: "/images/products/prod3.jpeg",
        description: "An intricately carved wooden sculpture.",
        price: 45.0,
        artist: "Lucia Fernandez",
        category: "Sculpture",
    },
    {
        id: "4",
        name: "Macrame Wall Hanging",
        imageUrl: "/images/products/prod4.jpeg",
        description: "A decorative macrame piece for your wall.",
        price: 35.5,
        artist: "Miguel Vargas",
        category: "Home Decor",
    },
    {
        id: "5",
        name: "Painted Clay Pot",
        imageUrl: "/images/products/prod5.jpeg",
        description: "Colorfully painted clay pot for indoor plants.",
        price: 19.75,
        artist: "Sofia Mendez",
        category: "Planter",
    },
    {
        id: "6",
        name: "Hand-stitched Pillow",
        imageUrl: "/images/products/prod6.jpeg",
        description: "Soft pillow with unique hand-stitched designs.",
        price: 22.0,
        artist: "Lucia Fernandez",
        category: "Textiles",
    },
    {
        id: "7",
        name: "Decorative Tray",
        imageUrl: "/images/products/prod7.jpeg",
        description: "Wooden tray with artisan carving and painting.",
        price: 28.99,
        artist: "Maria Lopez",
        category: "Kitchenware",
    },
    {
        id: "8",
        name: "Miniature House Set",
        imageUrl: "/images/products/prod8.jpeg",
        description: "Mini hand-painted ceramic house set.",
        price: 17.5,
        artist: "Jorge Ramirez",
        category: "Miniatures",
    },
    {
        id: "9",
        name: "Handmade Soap Bars",
        imageUrl: "/images/products/prod9.jpeg",
        description: "Aromatic and natural soap bars set of 3.",
        price: 12.0,
        artist: "Miguel Vargas",
        category: "Self-care",
    },
    {
        id: "10",
        name: "Crochet Tote Bag",
        imageUrl: "/images/products/prod10.jpeg",
        description: "Durable and stylish hand-crocheted bag.",
        price: 32.25,
        artist: "Sofia Mendez",
        category: "Accessories",
    },
    {
        id: "11",
        name: "Beaded Necklace",
        imageUrl: "/images/products/prod11.jpeg",
        description: "Colorful beaded necklace made by hand.",
        price: 16.95,
        artist: "Maria Lopez",
        category: "Jewelry",
    },
    ];